###########################################################
# This action is used to grasp an object by its name in
# the PlanningScene. The group used for planning along with
# its config must also be given.

# name of the object that shall be grasped
string object_name

# planning group with config name
GraspConfigSet[] grasp_config_sets

# The maximum amount of time the motion planner is allowed to plan for
float64 allowed_planning_time

# Planning options
moveit_msgs/PlanningOptions planning_options

---

# The overall result of the pickup attempt
moveit_msgs/MoveItErrorCodes error_code

# The performed grasp, if attempt was successful
moveit_msgs/Grasp grasp

---

# The internal state that the pickup action currently is in
string state
